export interface AudioTrack {
  id: string;
  title: string;
  src: string;
}

export interface AudiobookItem {
  slug: string;
  titleHindi: string;
  titleEnglish: string;
  subtitleHindi: string;
  subtitleEnglish: string;
  moodHindi: string;
  moodEnglish: string;
  accent: string;
  tracks: AudioTrack[];
}

function makeTracks(slug: string, titles: string[]): AudioTrack[] {
  return titles.map((title, index) => {
    const chapter = String(index + 1).padStart(2, '0');
    return {
      id: `${slug}-${chapter}`,
      title,
      src: `/library/audiobooks/${slug}/chapter-${chapter}.mp3`,
    };
  });
}

export const HINDI_AUDIOBOOKS: AudiobookItem[] = [
  {
    slug: 'main-kaun-hoon',
    titleHindi: 'मैं कौन हूँ',
    titleEnglish: 'Who Am I',
    subtitleHindi: 'साधक ही भ्रम है',
    subtitleEnglish: 'The Seeker Is the Illusion',
    moodHindi: 'खोज से विश्राम तक',
    moodEnglish: 'From seeking to stillness',
    accent: '#d4a843',
    tracks: makeTracks('main-kaun-hoon', [
      'श्रवण प्रारंभ',
      'लेखक नोट - मैंने यह पुस्तक क्यों लिखी',
      'अध्याय 1 - पहली भूल: मैं अभी वहाँ नहीं पहुँचा',
      'अध्याय 2 - साधक विचारों से बनी एक पहचान',
      'अध्याय 3 - जागरण उपलब्धि क्यों नहीं हो सकता',
      'अध्याय 4 - आध्यात्मिक अनुभवों का जाल',
      'अध्याय 5 - गुरु, विधि और छिपी हुई निर्भरता',
      'अध्याय 6 - खोज एक सूक्ष्म पलायन',
      'अध्याय 7 - जब खोज शांत होने लगती है',
      'अध्याय 8 - साधक को कौन जान रहा है',
      'अध्याय 9 - कोई अंतिम विस्फोट नहीं, केवल सरल पहचान',
      'अध्याय 10 - बनने के बोझ के बिना जीना',
      'समापन संदेश - अंतिम मौन स्पर्श',
      'श्रवण समापन',
    ]),
  },
  {
    slug: 'maya-aur-man',
    titleHindi: 'माया और मन',
    titleEnglish: 'Maya and Mind',
    subtitleHindi: 'विचार, भ्रम और जागृति की पहचान',
    subtitleEnglish: 'Thought, illusion and the recognition of awakening',
    moodHindi: 'मन को देखने की कला',
    moodEnglish: 'Seeing the movement of mind',
    accent: '#b9c76a',
    tracks: makeTracks('maya-aur-man', [
      'श्रवण प्रारंभ',
      'माया क्या है - मन का जन्म',
      'विचारों का जाल और मैं का भ्रम',
      'सुख-दुःख का पेंडुलम - मन की चाल',
      'साक्षीभाव - भ्रम से जागने की महा औषधि',
      'जागृति - जब माया का पर्दा गिरता है',
      'श्रवण समापन',
    ]),
  },
  {
    slug: 'sakshibhav',
    titleHindi: 'साक्षीभाव',
    titleEnglish: 'Witnessing',
    subtitleHindi: 'देखना, रोकना नहीं',
    subtitleEnglish: 'Seeing without suppression',
    moodHindi: 'प्रतिक्रिया से उपस्थिति तक',
    moodEnglish: 'From reaction to presence',
    accent: '#8dbf9d',
    tracks: makeTracks('sakshibhav', [
      'श्रवण प्रारंभ',
      'अध्याय 1 - साक्षीभाव क्या है',
      'अध्याय 2 - विचारों को रोकना नहीं, देखना है',
      'अध्याय 3 - भावनाओं के बीच शांत रहना',
      'अध्याय 4 - क्रोध, भय और चिंता को कैसे देखें',
      'अध्याय 5 - संबंधों में साक्षीभाव',
      'अध्याय 6 - काम, पैसा और जिम्मेदारी के बीच जागरूकता',
      'अध्याय 7 - शरीर, बीमारी और थकान को देखना',
      'अध्याय 8 - अकेलेपन में उपस्थित होना',
      'अध्याय 9 - प्रतिक्रिया से उत्तर तक',
      'अध्याय 10 - साक्षीभाव से सहज जीवन',
      'श्रवण समापन',
    ]),
  },
  {
    slug: 'karuna-ka-aadhar',
    titleHindi: 'करुणा का आधार',
    titleEnglish: 'The Ground of Compassion',
    subtitleHindi: 'दर्द के भीतर खुलता हुआ हृदय',
    subtitleEnglish: 'The heart opening inside pain',
    moodHindi: 'कठोरता से कोमलता तक',
    moodEnglish: 'From hardness to tenderness',
    accent: '#d8a36f',
    tracks: makeTracks('karuna-ka-aadhar', [
      'श्रवण प्रारंभ',
      'अध्याय 1 - दर्द से भागना क्यों बंद करना होगा',
      'अध्याय 2 - घाव कोई शत्रु नहीं, बंद दरवाज़ा है',
      'अध्याय 3 - Compassionate Anchor क्या है',
      'अध्याय 4 - शरीर में रुके हुए दुख को देखना',
      'अध्याय 5 - अस्वीकार, अकेलापन और प्रेम की भूख',
      'अध्याय 6 - अपराधबोध और शर्म का पिघलना',
      'अध्याय 7 - संबंधों की चोट और आंतरिक स्वतंत्रता',
      'अध्याय 8 - रोना, टूटना और खुलना',
      'अध्याय 9 - समर्पण: जब मन हारता नहीं, नरम पड़ता है',
      'अध्याय 10 - करुणा में विश्राम',
      'श्रवण समापन',
    ]),
  },
  {
    slug: 'bodhgaya-samvad',
    titleHindi: 'बोधगया संवाद',
    titleEnglish: 'Bodhgaya Dialogues',
    subtitleHindi: 'प्रश्न, मौन और प्रत्यक्षता',
    subtitleEnglish: 'Questions, silence and direct seeing',
    moodHindi: 'संवाद से दर्शन तक',
    moodEnglish: 'From dialogue to direct seeing',
    accent: '#c89bff',
    tracks: makeTracks('bodhgaya-samvad', [
      'श्रवण प्रारंभ',
      'संवाद 1 - मैं कौन हूँ',
      'संवाद 2 - क्या जागरण कोई अनुभव है',
      'संवाद 3 - क्या गुरु जरूरी है',
      'संवाद 4 - ध्यान का असली अर्थ क्या है',
      'संवाद 5 - क्या संसार सच है या माया',
      'संवाद 6 - प्रेम और आसक्ति में अंतर क्या है',
      'संवाद 7 - दुःख क्यों आता है',
      'संवाद 8 - साधना करनी है या बस देखना है',
      'संवाद 9 - जागरण के बाद जीवन कैसा होता है',
      'संवाद 10 - बोधिवृक्ष के नीचे अंतिम संवाद',
      'श्रवण समापन',
    ]),
  },
];

export const ENGLISH_AUDIOBOOKS: AudiobookItem[] = [
  {
    slug: 'the-seeker-is-the-illusion-en',
    titleHindi: 'The Seeker Is the Illusion',
    titleEnglish: 'The Seeker Is the Illusion',
    subtitleHindi: 'A quiet return from seeking to seeing',
    subtitleEnglish: 'A quiet return from seeking to seeing',
    moodHindi: 'Self-inquiry in listening',
    moodEnglish: 'Self-inquiry in listening',
    accent: '#d4a843',
    tracks: makeTracks('the-seeker-is-the-illusion-en', [
      "Author's Note",
      'Chapter 1 - The First Mistake: I Have Not Arrived Yet',
      'Chapter 2 - The Seeker as a Thought Identity',
      'Chapter 3 - Why Enlightenment Cannot Be Achieved',
      'Chapter 4 - The Trap of Spiritual Experiences',
      'Chapter 5 - Guru, Method and Hidden Dependency',
      'Chapter 6 - Seeking as a Subtle Escape',
      'Chapter 7 - When the Search Begins to Grow Quiet',
      'Chapter 8 - Who Knows the Seeker?',
      'Chapter 9 - No Final Explosion, Only Simple Recognition',
      'Chapter 10 - Living Without the Burden of Becoming',
      'Closing Transmission',
    ]),
  },
  {
    slug: 'maya-and-mind-en',
    titleHindi: 'Maya and Mind',
    titleEnglish: 'Maya and Mind',
    subtitleHindi: 'Thought, illusion and the recognition of awakening',
    subtitleEnglish: 'Thought, illusion and the recognition of awakening',
    moodHindi: 'Seeing the movement of mind',
    moodEnglish: 'Seeing the movement of mind',
    accent: '#b9c76a',
    tracks: makeTracks('maya-and-mind-en', [
      'What Is Maya? The Birth of the Mind',
      'The Web of Thoughts and the Illusion of I',
      'The Pendulum of Joy and Sorrow: The Trick of the Mind',
      'Sakshibhav: The Great Medicine for Waking from Illusion',
      'Awakening: When the Veil Falls',
    ]),
  },
  {
    slug: 'witnessing-awareness-en',
    titleHindi: 'Witnessing Awareness',
    titleEnglish: 'Witnessing Awareness',
    subtitleHindi: 'Seeing without suppression',
    subtitleEnglish: 'Seeing without suppression',
    moodHindi: 'From reaction to presence',
    moodEnglish: 'From reaction to presence',
    accent: '#8dbf9d',
    tracks: makeTracks('witnessing-awareness-en', [
      'Audiobook Intro',
      'Chapter 1 - What Witnessing Awareness Really Is',
      'Chapter 2 - Do Not Stop Thoughts, See Them',
      'Chapter 3 - Staying Gentle in the Middle of Emotions',
      'Chapter 4 - Anger, Fear and Anxiety as Doorways',
      'Chapter 5 - Witnessing in Relationships',
      'Chapter 6 - Work, Money and Responsibility',
      'Chapter 7 - The Body, Illness and Fatigue',
      'Chapter 8 - Meeting Loneliness Without Running',
      'Chapter 9 - From Reaction to Response',
      'Chapter 10 - Living as the Witness',
      'Audiobook Outro',
    ]),
  },
  {
    slug: 'the-compassionate-anchor-en',
    titleHindi: 'The Compassionate Anchor',
    titleEnglish: 'The Compassionate Anchor',
    subtitleHindi: 'Meeting pain with awareness and tenderness',
    subtitleEnglish: 'Meeting pain with awareness and tenderness',
    moodHindi: 'From hardness to tenderness',
    moodEnglish: 'From hardness to tenderness',
    accent: '#d8a36f',
    tracks: makeTracks('the-compassionate-anchor-en', [
      'Audiobook Intro',
      'Chapter 1 - Why Pain Must Be Met Gently',
      'Chapter 2 - The Wound Is a Closed Door',
      'Chapter 3 - What the Compassionate Anchor Means',
      'Chapter 4 - Feeling Pain in the Body',
      'Chapter 5 - Rejection, Loneliness and the Hunger for Love',
      'Chapter 6 - Guilt and Shame Melting in Awareness',
      'Chapter 7 - Relationship Wounds and Inner Freedom',
      'Chapter 8 - Tears, Breaking and Opening',
      'Chapter 9 - Surrender as Softening',
      'Chapter 10 - Resting in Compassion',
      'Audiobook Outro',
    ]),
  },
  {
    slug: 'bodhgaya-dialogues-en',
    titleHindi: 'Bodhgaya Dialogues',
    titleEnglish: 'Bodhgaya Dialogues',
    subtitleHindi: 'Questions, silence and direct seeing',
    subtitleEnglish: 'Questions, silence and direct seeing',
    moodHindi: 'From dialogue to direct seeing',
    moodEnglish: 'From dialogue to direct seeing',
    accent: '#c89bff',
    tracks: makeTracks('bodhgaya-dialogues-en', [
      'Audiobook Intro',
      'Dialogue 1 - Who Am I?',
      'Dialogue 2 - Is Awakening an Experience?',
      'Dialogue 3 - Is a Guru Necessary?',
      'Dialogue 4 - What Is Real Meditation?',
      'Dialogue 5 - Is the World Real or Maya?',
      'Dialogue 6 - What Is the Difference Between Love and Attachment?',
      'Dialogue 7 - Why Does Suffering Come?',
      'Dialogue 8 - Should I Practice or Only Watch?',
      'Dialogue 9 - What Is Life After Awakening?',
      'Dialogue 10 - The Final Conversation Under the Bodhi Tree',
      'Audiobook Outro',
    ]),
  },
];
